contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #treeval channel"
    url: https://nfcore.slack.com/channels/treeval
    about: Discussion about the sanger-tol/treeval pipeline
